namespace: fleet-mc-helm-example
helm:
  values:
    any-custom: value
    variableName: global.fleet.clusterLabels.LABELNAME
targetCustomizations:
- name: dev
  helm:
    values:
      any-custom: value
      variableName: global.fleet.clusterLabels.LABELNAME
      replication: false
      prometheus:
        prometheusSpec:
          additionalAlertRelabelConfigs:
            - source_labels: [__address__]
              target_label: cluster
              additional_list:
              - replacement: global.fleet.clusterLabels.management.cattle.io/cluster-display-name
  clusterSelector:
    matchLabels:
      env: dev

- name: test
  helm:
    values:
      replicas: 3
      any-custom: value
      variableName: global.fleet.clusterLabels.LABELNAME
  clusterSelector:
    matchLabels:
      env: test

- name: prod
  helm:
    values:
      any-custom: value
      variableName: global.fleet.clusterLabels.LABELNAME
      serviceType: LoadBalancer
      replicas: 3
  clusterSelector:
    matchLabels:
      env: prod
- name: test3
  helm:
    chart: simple-chart
    valuesFrom:
      - secretKeyRef:
          name: secret-values
          namespace: default
          key: values.yaml
        configMapKeyRef:
          name: configmap-values
          namespace: default
          key: values.yaml
